<?php
use SNOWGIRL_CORE\View\Widget\Form\Subscribe;

/** @var Subscribe $this */
?>

<div class="form-group">
    <label><input class="form-control" name="name" placeholder="<?php echo $this->texts['namePlaceholder'] ?>"
                  aria-label="name" type="text" required></label>
</div>

<div class="form-group">
    <label><input class="form-control" name="email" placeholder="<?php echo $this->texts['emailPlaceholder'] ?>"
                  aria-label="email" type="email" required></label>
</div>

<?php if ($view = (string)$this->getCaptcha()) { ?>
    <div class="form-group">
        <?php echo $view ?>
    </div>
<?php } ?>

<button class="btn btn-primary btn-sm" type="submit">
    <span class="fa fa-rss"></span>
    <?php echo $this->texts['submitButton'] ?>
</button>