<?php

use SNOWGIRL_CORE\View\Layout;
use SNOWGIRL_CORE\Script\Css;

/** @var Layout $this */
/** @var Css $css */
$title = $this->title ?? $this->h1;
?>
<head<?php echo $this->headPrefix ?>>
    <?php foreach ($this->domains as $v) { ?>
        <link rel="dns-prefetch" href="<?php echo $v ?>">
    <?php } ?>

    <base href="<?php echo $this->baseHref ?>"/>
    <meta charset="utf-8">

    <title><?php echo $title ? (htmlspecialchars($title) . ' | ') : '' ?><?php echo $this->site ?></title>

    <?php foreach ($this->meta as $k => $v) { ?>
        <meta name="<?php echo $k ?>" content="<?php echo htmlspecialchars($v) ?>">
    <?php } ?>

    <?php foreach ($this->headLinks as $k => $v) { ?>
        <link rel="<?php echo $k ?>" href="<?php echo $v ?>">
    <?php } ?>

    <?php foreach ($this->metaProperties as $k => $v) { ?>
        <meta property="<?php echo $k ?>" content="<?php echo htmlspecialchars($v) ?>">
    <?php } ?>

    <?php foreach ($this->headCss as $css) { ?>
        <?php echo $css ?>
    <?php } ?>

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>