<?php

use SNOWGIRL_CORE\View\Layout\Outer;


/** @var Outer $this */
?>

<header class="header">
    <div class="container">
        <div class="row">
            <div class="header-col col-xs-12 col-md-3 col-lg-4 header-logo">
                <div class="header-inner">
                    <?php if ($this->mobileBackBtn) { ?>
                        <button type="button" class="btn btn-back" aria-label="<?php echo trans('layout.get-back') ?>">
                            <span class="fa fa-angle-left"></span>
                        </button>
                    <?php } ?>

                    <?php if ('/' == $this->currentUri) { ?>
                        <span class="header-logo-link"><?php echo $this->site ?></span>
                    <?php } else { ?>
                        <a class="header-logo-link" href="/"><?php echo $this->site ?></a>
                    <?php } ?>

                    <?php if ($this->headerNav) { ?>
                        <button type="button"
                                class="btn btn-toggle-sm-nav"
                                aria-label="<?php echo trans('layout.toggle-nav') ?>"
                                data-icon-toggle="fa fa-fw fa-ellipsis-h">
                            <span class="fa fa-fw fa-ellipsis-v"></span>
                        </button>
                    <?php } ?>

                    <?php if ($this->headerSearch) { ?>
                        <button type="button"
                                class="btn btn-toggle-sm-web"
                                aria-label="<?php echo trans('layout.toggle-search') ?>"
                                data-icon-toggle="fa fa-fw fa-times">
                            <span class="fa fa-fw fa-search"></span>
                        </button>
                    <?php } ?>
                </div>
            </div>

            <div class="header-col col-xs-12 col-md-4 col-lg-4 header-web obj-toggle-sm-web" itemscope
                 itemtype="http://schema.org/WebSite">
                <link itemprop="url" href="<?php echo $this->makeLink('default') ?>">
                <div class="header-inner">
                    <?php if ($this->headerSearch && $view = $this->app->views->searchForm($this)) { ?>
                        <?php echo $view
                            ->addNodeAttr('itemprop', 'potentialAction')
                            ->addDomClass('header-search')
                            ->setParam('action', $this->app->router->makeLink('default', 'catalog'))
                            ->setParam('large', true)
                            ->setParam('suggestions', true)
                            ->setParam('suggestionsLimit', 5)
                            ->setParam('microdata', true)
                            ->setParam('events', true)
                            ->setParam('eventCategory', 'header search')
                            ->setParam('submitButtonText', true)
                        ?>
                    <?php } ?>
                </div>
            </div>

            <div class="header-col col-xs-12 col-md-5 col-lg-4 header-nav obj-toggle-sm-nav nav-sm"
                 aria-label="<?php echo trans('layout.navigation') ?>" itemscope itemtype="http://schema.org/SiteNavigationElement">
                <div class="header-inner">
                    <?php if ($this->headerNav) { ?>
                        <nav>
                            <?php foreach ($this->headerNav as $text => $href) { ?>
                                <?php if ($this->currentUri == $href) { ?>
                                    <span class="active nav-item">
                                        <span class="active" itemprop="name"><?php echo $text ?></span>
                                        <link itemprop="url" href="<?php echo $href ?>">
                                    </span>
                                <?php } else { ?>
                                    <a href="<?php echo $href ?>" class="nav-item" itemprop="url">
                                        <span itemprop="name"><?php echo $text ?></span>
                                    </a>
                                <?php } ?>
                            <?php } ?>
                        </nav>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</header>
