<?php
use SNOWGIRL_CORE\View\Layout;

/** @var Layout $this */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->lang ?>">
<?php echo $this->head ?>
<body class="vs">
<?php echo $this->banner ?>
<?php echo $this->header ?>
<?php echo $this->breadcrumbs ?>
<?php echo $this->messages ?>
<?php echo $this->content ?>
<?php echo $this->about ?>
<?php echo $this->footer ?>
<?php echo $this->bottom ?>
</body>
</html>